apiVersion: batch/v1
kind: Job
metadata:
  name: joinquest-db-migrate
  namespace: joinquest
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: docker.io/scruffyprodigy/joinquest-backend:latest
          command: ["./migrate", "-action=up"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pg-dsn
                  key: DATABASE_URL
