-- "Away" is socket alive, attention gone. It is a different signal from
-- "disconnected" (socket gone, user_presence.disconnected_at) and the two are
-- independent: a player can be connected-and-away, connected-and-present, or
-- disconnected. connection_count cannot answer it, because a backgrounded tab
-- holds live sockets exactly like a foregrounded one.
--
-- Keyed by document rather than by socket. One document opens three independent
-- graphql-ws clients (queue.js, rooms.js, tables.js), and they all share one
-- document.visibilityState -- so visibility is a property of the document, and
-- counting sockets would multiply one answer by three.
CREATE TABLE user_document_visibility (
    -- Generated by the client, once per document load. Not a session id and not
    -- persisted across reloads: a reloaded page is a new document and gets a new
    -- row, while the old one is cleared when its sockets close.
    document_id UUID PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    visible     BOOLEAN NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_user_document_visibility_user ON user_document_visibility (user_id);

-- Absence of rows means "no client ever reported", which reads as PRESENT, not
-- away. That default is deliberate and is the only safe direction: an older
-- client, a JS error, or a browser that never fires visibilitychange would
-- otherwise have every player read as away, and a seat-hold would fire for
-- people sitting and watching. Unknown means present, which is the behaviour
-- that shipped before this table existed.
--
-- So "away" requires positive evidence on both halves: the user holds a live
-- socket, at least one document has reported, and none of the reports say
-- visible.
