// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type ModeRequirementNode interface {
	IsModeRequirementNode()
	GetLabel() string
}

type Account struct {
	User              *User           `json:"user"`
	Emails            []*UserEmail    `json:"emails"`
	Identities        []*UserIdentity `json:"identities"`
	SignInMethodCount int             `json:"signInMethodCount"`
}

type ActiveIntent struct {
	QueueID         *string     `json:"queueId,omitempty"`
	GameID          string      `json:"gameId"`
	GameName        string      `json:"gameName"`
	ModeName        *string     `json:"modeName,omitempty"`
	SeatDisplayName *string     `json:"seatDisplayName,omitempty"`
	Status          QueueStatus `json:"status"`
	QueuedCount     *int        `json:"queuedCount,omitempty"`
	QueuePath       *string     `json:"queuePath,omitempty"`
	// Human label for queuePath from the mode seatTemplate (e.g. Clue Giver).
	QueuePathDisplayName *string `json:"queuePathDisplayName,omitempty"`
	JoinURL              *string `json:"joinUrl,omitempty"`
	// Remaining role needs for the active forming match (catalog wait).
	FormingGaps []*QueuePathGap `json:"formingGaps"`
}

type CatalogTagOption struct {
	ID          string `json:"id"`
	Label       string `json:"label"`
	Description string `json:"description"`
}

type ConnectMyGameInput struct {
	GameID string `json:"gameId"`
	// Optional new public HTTPS API origin. Omit to retry the current URL.
	APIBaseURL *string `json:"apiBaseUrl,omitempty"`
}

type ConnectMyGamePayload struct {
	Game         *Game   `json:"game"`
	Connected    bool    `json:"connected"`
	Changed      bool    `json:"changed"`
	ConnectError *string `json:"connectError,omitempty"`
}

type CreateDeveloperAPIKeyPayload struct {
	APIKey *DeveloperAPIKey `json:"apiKey"`
	Secret string           `json:"secret"`
}

type DeveloperAPIKey struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	KeyPrefix  string     `json:"keyPrefix"`
	CreatedAt  time.Time  `json:"createdAt"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
}

type DigitalGood struct {
	ID          string  `json:"id"`
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Game        *Game   `json:"game,omitempty"`
}

type EmailLinkPreview struct {
	Email                  string  `json:"email"`
	WillMergeAccounts      bool    `json:"willMergeAccounts"`
	MergeSourceDisplayName *string `json:"mergeSourceDisplayName,omitempty"`
}

type Entitlement struct {
	Good      *DigitalGood `json:"good"`
	Quantity  int          `json:"quantity"`
	GrantedAt time.Time    `json:"grantedAt"`
}

type Game struct {
	ID               string     `json:"id"`
	Name             string     `json:"name"`
	CreatedAt        time.Time  `json:"createdAt"`
	ActiveSessions   []*Session `json:"activeSessions"`
	Slug             *string    `json:"slug,omitempty"`
	APIBaseURL       *string    `json:"apiBaseUrl,omitempty"`
	ManifestSyncedAt *time.Time `json:"manifestSyncedAt,omitempty"`
	ManifestHash     *string    `json:"manifestHash,omitempty"`
	GameVersion      *string    `json:"gameVersion,omitempty"`
	// Square catalog icon (1:1). Used on room table cards.
	IconURL string `json:"iconUrl"`
	// Wide hero banner for the game detail page.
	HeroURL string `json:"heroUrl"`
	// Optional catalog-only hero (4:3). Falls back to heroUrl when unset.
	CatalogHeroURL *string `json:"catalogHeroUrl,omitempty"`
	// Transparent wordmark composited over the catalog card art. Null when the game has none.
	TitleArt *GameTitleArt `json:"titleArt,omitempty"`
	// Long-form copy for the game detail page (maps to games.description).
	LongDescription  *string  `json:"longDescription,omitempty"`
	ShortDescription *string  `json:"shortDescription,omitempty"`
	HowToPlay        *string  `json:"howToPlay,omitempty"`
	TutorialURL      *string  `json:"tutorialUrl,omitempty"`
	Screenshots      []string `json:"screenshots"`
	Tags             []string `json:"tags"`
	// Developer-chosen hex accent (#rrggbb). Null falls back to the slug-hashed palette color.
	AccentColor *string `json:"accentColor,omitempty"`
	// Live player counts for the catalog card. Served from a short-lived whole-catalog snapshot.
	PlayerActivity    *GamePlayerActivity     `json:"playerActivity"`
	Modes             []*GameMode             `json:"modes"`
	Visibility        GameVisibility          `json:"visibility"`
	ContactEmail      *string                 `json:"contactEmail,omitempty"`
	WebsiteURL        *string                 `json:"websiteUrl,omitempty"`
	CommunityURL      *string                 `json:"communityUrl,omitempty"`
	OwnerUserID       *string                 `json:"ownerUserId,omitempty"`
	IntegrationChecks []*GameIntegrationCheck `json:"integrationChecks"`
}

type GameIntegrationCheck struct {
	CheckID string                 `json:"checkId"`
	Status  IntegrationCheckStatus `json:"status"`
	Message *string                `json:"message,omitempty"`
	Detail  *string                `json:"detail,omitempty"`
	RanAt   *time.Time             `json:"ranAt,omitempty"`
}

type GameMode struct {
	ID          string          `json:"id"`
	ModeKey     string          `json:"modeKey"`
	DisplayName string          `json:"displayName"`
	MinPlayers  int             `json:"minPlayers"`
	MaxPlayers  int             `json:"maxPlayers"`
	Status      string          `json:"status"`
	Seats       []*GameModeSeat `json:"seats"`
	// Join options with human labels and per-cohort fire sizes.
	QueuePaths  []*GameModeQueuePath `json:"queuePaths"`
	Queues      []*ModeQueue         `json:"queues"`
	Eligibility *ModeEligibility     `json:"eligibility,omitempty"`
}

// One join bucket from seatTemplate (composition modes).
type GameModeQueuePath struct {
	QueuePath      string `json:"queuePath"`
	DisplayName    string `json:"displayName"`
	MinPlayers     int    `json:"minPlayers"`
	MaxPlayers     int    `json:"maxPlayers"`
	PlayersToStart int    `json:"playersToStart"`
}

type GameModeSeat struct {
	SeatKey string  `json:"seatKey"`
	Team    *string `json:"team,omitempty"`
	Role    *string `json:"role,omitempty"`
	// Lobby join bucket derived from seatTemplate (empty for fifo modes).
	QueuePath *string `json:"queuePath,omitempty"`
	SortOrder int     `json:"sortOrder"`
}

// Players a game has right now. Playing and queued are different people, not two views of one number.
type GamePlayerActivity struct {
	// Players seated in a live session of this game.
	Playing int `json:"playing"`
	// Players waiting in this game's queues for a match to fill.
	Queued int `json:"queued"`
}

// The game's name as artwork, drawn over the catalog card's hero.
//
// Placement travels with the mark because it varies per lockup: a wide one wants
// most of the card's width, a compact one a third of it. Insets and the height cap
// are constant across the design and live in the client.
type GameTitleArt struct {
	// Transparent image (typically .webp) carrying the game's name.
	URL string `json:"url"`
	// Corner the mark is pinned to: top-left, top-center, bottom-left, bottom-center or middle-center.
	Anchor string `json:"anchor"`
	// Rendered width as a percentage of the card's width, so the mark scales with the card.
	WidthPct float64 `json:"widthPct"`
}

type JoinResult struct {
	Queued      bool    `json:"queued"`
	SessionID   *string `json:"sessionId,omitempty"`
	JoinURL     *string `json:"joinUrl,omitempty"`
	QueuedCount *int    `json:"queuedCount,omitempty"`
	QueuePath   *string `json:"queuePath,omitempty"`
	Message     *string `json:"message,omitempty"`
}

type MatchParticipantResult struct {
	// No email: a queue match introduces strangers, so the roster must not expose contact details.
	User       *PublicPlayer `json:"user"`
	Role       *string       `json:"role,omitempty"`
	Finished   bool          `json:"finished"`
	FinishedAt *time.Time    `json:"finishedAt,omitempty"`
	// Null when the game never reported this player — distinct from the player merely returning.
	Reason    *PlayerFinishReason `json:"reason,omitempty"`
	Placement *int                `json:"placement,omitempty"`
	Winner    bool                `json:"winner"`
	Regroup   RegroupState        `json:"regroup"`
}

type MatchResult struct {
	MatchID string `json:"matchId"`
	Game    *Game  `json:"game"`
	// Null when the game reported no result.
	Status   *MatchResultStatus `json:"status,omitempty"`
	Reported bool               `json:"reported"`
	// True when the session is completed; drives "Final standings" vs "Results so far".
	Complete     bool                      `json:"complete"`
	EndedAt      *time.Time                `json:"endedAt,omitempty"`
	Participants []*MatchParticipantResult `json:"participants"`
	// Set once a regroup table exists, so the client can route to it.
	RegroupInviteCode *string `json:"regroupInviteCode,omitempty"`
}

type ModeEligibility struct {
	Accessible    bool                `json:"accessible"`
	Reason        *string             `json:"reason,omitempty"`
	Requirement   ModeRequirementNode `json:"requirement,omitempty"`
	UnlockModeKey *string             `json:"unlockModeKey,omitempty"`
}

type ModeQueue struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	PlayersToStart int    `json:"playersToStart"`
	Status         string `json:"status"`
	WaitingCount   int    `json:"waitingCount"`
}

type Mutation struct {
}

type MyGameCredentials struct {
	ServiceToken  string `json:"serviceToken"`
	WebhookSecret string `json:"webhookSecret"`
}

type MyTableSeat struct {
	TableID         string `json:"tableId"`
	RoomID          string `json:"roomId"`
	InviteCode      string `json:"inviteCode"`
	GameID          string `json:"gameId"`
	GameName        string `json:"gameName"`
	ModeID          string `json:"modeId"`
	ModeName        string `json:"modeName"`
	SeatKey         string `json:"seatKey"`
	SeatDisplayName string `json:"seatDisplayName"`
	// forming while seated at a table; started when the table has launched a session.
	Status         string          `json:"status"`
	JoinURL        *string         `json:"joinUrl,omitempty"`
	BackfillActive bool            `json:"backfillActive"`
	FormingGaps    []*QueuePathGap `json:"formingGaps"`
}

type PartyMemberInput struct {
	UserID    string `json:"userId"`
	QueuePath string `json:"queuePath"`
}

type PartyNodeInput struct {
	Role     *string             `json:"role,omitempty"`
	Children []*PartyNodeInput   `json:"children,omitempty"`
	Members  []*PartyMemberInput `json:"members,omitempty"`
}

type PlayAgainResult struct {
	Table      *Table `json:"table"`
	InviteCode string `json:"inviteCode"`
	Seated     bool   `json:"seated"`
}

type PublicPlayer struct {
	ID           string        `json:"id"`
	DisplayName  *string       `json:"displayName,omitempty"`
	AvatarURL    *string       `json:"avatarUrl,omitempty"`
	AvatarSource *AvatarSource `json:"avatarSource,omitempty"`
}

type Query struct {
}

type QueuePathGap struct {
	QueuePath   string `json:"queuePath"`
	DisplayName string `json:"displayName"`
	Assigned    int    `json:"assigned"`
	Needed      int    `json:"needed"`
}

type QueueUpdate struct {
	GameID      string          `json:"gameId"`
	QueueID     string          `json:"queueId"`
	Status      QueueStatus     `json:"status"`
	SessionID   *string         `json:"sessionId,omitempty"`
	JoinURL     *string         `json:"joinUrl,omitempty"`
	QueuedCount int             `json:"queuedCount"`
	Message     *string         `json:"message,omitempty"`
	FormingGaps []*QueuePathGap `json:"formingGaps"`
}

type RegisterGameInput struct {
	Slug        string  `json:"slug"`
	APIBaseURL  string  `json:"apiBaseUrl"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	// Square catalog icon (1:1). Used on room table cards; required.
	IconURL string `json:"iconUrl"`
	// Wide catalog hero banner (5:2 aspect ratio). Top of catalog game card; required.
	HeroURL string `json:"heroUrl"`
}

type RegisterGamePayload struct {
	Game          *Game  `json:"game"`
	WebhookSecret string `json:"webhookSecret"`
	// Per-game credential for provision + player GraphQL (derived from game id).
	ServiceToken string `json:"serviceToken"`
}

type RegisterMyGameInput struct {
	Slug             string  `json:"slug"`
	Name             string  `json:"name"`
	ShortDescription string  `json:"shortDescription"`
	APIBaseURL       string  `json:"apiBaseUrl"`
	ContactEmail     string  `json:"contactEmail"`
	WebsiteURL       *string `json:"websiteUrl,omitempty"`
	CommunityURL     *string `json:"communityUrl,omitempty"`
}

type RegisterMyGamePayload struct {
	Game          *Game   `json:"game"`
	WebhookSecret string  `json:"webhookSecret"`
	ServiceToken  string  `json:"serviceToken"`
	Connected     bool    `json:"connected"`
	ConnectError  *string `json:"connectError,omitempty"`
}

type RequirementGroup struct {
	Label    string                `json:"label"`
	Operator RequirementOperator   `json:"operator"`
	Children []ModeRequirementNode `json:"children"`
}

func (RequirementGroup) IsModeRequirementNode() {}
func (this RequirementGroup) GetLabel() string  { return this.Label }

type RequirementLeaf struct {
	Label   string `json:"label"`
	Current int    `json:"current"`
	Target  int    `json:"target"`
}

func (RequirementLeaf) IsModeRequirementNode() {}
func (this RequirementLeaf) GetLabel() string  { return this.Label }

type ReturnDestination struct {
	Path string `json:"path"`
	Kind string `json:"kind"`
}

type Room struct {
	ID         string         `json:"id"`
	InviteCode string         `json:"inviteCode"`
	JoinURL    string         `json:"joinUrl"`
	Host       *User          `json:"host"`
	Members    []*User        `json:"members"`
	Messages   []*RoomMessage `json:"messages"`
	Tables     []*Table       `json:"tables"`
}

type RoomMessage struct {
	ID        string    `json:"id"`
	Author    *User     `json:"author"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"createdAt"`
}

type Session struct {
	ID        string        `json:"id"`
	Game      *Game         `json:"game"`
	Status    SessionStatus `json:"status"`
	CreatedAt time.Time     `json:"createdAt"`
	Players   []*User       `json:"players"`
}

type SpiritAnimalAnswer struct {
	ID    string `json:"id"`
	Label string `json:"label"`
}

type SpiritAnimalCardQuestion struct {
	Slot                 string                `json:"slot"`
	SlotName             string                `json:"slotName"`
	Card                 string                `json:"card"`
	CardMeaningInGeneral string                `json:"cardMeaningInGeneral"`
	CardMeaningForSlot   string                `json:"cardMeaningForSlot"`
	Question             string                `json:"question"`
	Answers              []*SpiritAnimalAnswer `json:"answers"`
}

type SpiritAnimalJourneyEligibility struct {
	CanBegin       bool       `json:"canBegin"`
	CooldownEndsAt *time.Time `json:"cooldownEndsAt,omitempty"`
	DaysRemaining  *int       `json:"daysRemaining,omitempty"`
}

type SpiritAnimalJourneySummary struct {
	Compass  string `json:"compass"`
	Coin     string `json:"coin"`
	Storm    string `json:"storm"`
	Campfire string `json:"campfire"`
	Beacon   string `json:"beacon"`
}

type SpiritAnimalPersonality struct {
	Overview       string                      `json:"overview"`
	JourneySummary *SpiritAnimalJourneySummary `json:"journeySummary"`
	CoreThemes     []string                    `json:"coreThemes"`
	Strengths      []string                    `json:"strengths"`
	Tensions       []string                    `json:"tensions"`
	SocialIdentity string                      `json:"socialIdentity"`
}

type SpiritAnimalReading struct {
	ID                string                      `json:"id"`
	Status            SpiritAnimalReadingStatus   `json:"status"`
	Draw              []int                       `json:"draw"`
	CardQuestions     []*SpiritAnimalCardQuestion `json:"cardQuestions,omitempty"`
	Personality       *SpiritAnimalPersonality    `json:"personality,omitempty"`
	MascotOverview    *string                     `json:"mascotOverview,omitempty"`
	Totems            []*SpiritAnimalTotem        `json:"totems,omitempty"`
	SelectedTotemName *string                     `json:"selectedTotemName,omitempty"`
	ErrorMessage      *string                     `json:"errorMessage,omitempty"`
	ImagesMissing     bool                        `json:"imagesMissing"`
	// When status is GENERATING_QUESTIONS or PROCESSING, when the current wait began.
	PhaseStartedAt *time.Time `json:"phaseStartedAt,omitempty"`
	// Approximate total seconds for the current processing phase, based on recent readings.
	EstimatedPhaseSeconds *int `json:"estimatedPhaseSeconds,omitempty"`
}

type SpiritAnimalTotem struct {
	Name                    string   `json:"name"`
	Animal                  string   `json:"animal"`
	SocialArchetype         string   `json:"socialArchetype"`
	CoreConcept             string   `json:"coreConcept"`
	ColorPalette            []string `json:"colorPalette"`
	PersonalitySummary      string   `json:"personalitySummary"`
	WhyThisAnimal           string   `json:"whyThisAnimal"`
	OriginStory             string   `json:"originStory"`
	ImageURL                *string  `json:"imageUrl,omitempty"`
	FitScore                *int     `json:"fitScore,omitempty"`
	Affinity                *string  `json:"affinity,omitempty"`
	ReadingEmphasis         *string  `json:"readingEmphasis,omitempty"`
	WhyThisAnimalMakesSense *string  `json:"whyThisAnimalMakesSense,omitempty"`
	WhyChooseThisAvatar     *string  `json:"whyChooseThisAvatar,omitempty"`
}

type StarterAvatar struct {
	Key      string `json:"key"`
	Name     string `json:"name"`
	Slot     string `json:"slot"`
	ImageURL string `json:"imageUrl"`
}

type Subscription struct {
}

type SyncMyGameManifestPayload struct {
	Game         *Game   `json:"game"`
	Changed      bool    `json:"changed"`
	ConnectError *string `json:"connectError,omitempty"`
}

type Table struct {
	ID                  string                     `json:"id"`
	Game                *Game                      `json:"game"`
	Mode                *GameMode                  `json:"mode"`
	CreatedAt           time.Time                  `json:"createdAt"`
	King                *User                      `json:"king,omitempty"`
	Seats               []*TableSeat               `json:"seats"`
	SeatSlots           []*TableSeatSlot           `json:"seatSlots"`
	CanStart            bool                       `json:"canStart"`
	CanDiscard          bool                       `json:"canDiscard"`
	LookForGroupOptions []*TableLookForGroupOption `json:"lookForGroupOptions"`
	// True when this table has started lobby backfill (forming match seeded from seats).
	BackfillActive bool `json:"backfillActive"`
	// Roles still needed to start via backfill or from current seated counts.
	FormingGaps []*QueuePathGap `json:"formingGaps"`
	// Originating match roster and regroup state; empty for tables not reached from a finished match.
	RegroupRoster []*MatchParticipantResult `json:"regroupRoster"`
}

type TableLookForGroupOption struct {
	QueueID   string `json:"queueId"`
	QueueName string `json:"queueName"`
	Visible   bool   `json:"visible"`
	Enabled   bool   `json:"enabled"`
}

type TableSeat struct {
	SeatKey  string    `json:"seatKey"`
	User     *User     `json:"user"`
	SeatedAt time.Time `json:"seatedAt"`
}

type TableSeatSlot struct {
	SeatKey     string  `json:"seatKey"`
	QueuePath   *string `json:"queuePath,omitempty"`
	DisplayName string  `json:"displayName"`
	TeamPrefix  *string `json:"teamPrefix,omitempty"`
	User        *User   `json:"user,omitempty"`
}

type UpdateMyGameMetadataInput struct {
	GameID           string   `json:"gameId"`
	Name             *string  `json:"name,omitempty"`
	ShortDescription *string  `json:"shortDescription,omitempty"`
	LongDescription  *string  `json:"longDescription,omitempty"`
	HowToPlay        *string  `json:"howToPlay,omitempty"`
	Tags             []string `json:"tags,omitempty"`
	ContactEmail     *string  `json:"contactEmail,omitempty"`
	WebsiteURL       *string  `json:"websiteUrl,omitempty"`
	CommunityURL     *string  `json:"communityUrl,omitempty"`
	// Hex catalog accent (#rrggbb or #rgb). Empty string resets to the default.
	AccentColor *string `json:"accentColor,omitempty"`
}

type User struct {
	ID           string          `json:"id"`
	Email        *string         `json:"email,omitempty"`
	DisplayName  *string         `json:"displayName,omitempty"`
	AvatarURL    *string         `json:"avatarUrl,omitempty"`
	AvatarKey    *string         `json:"avatarKey,omitempty"`
	AvatarSource *AvatarSource   `json:"avatarSource,omitempty"`
	CreatedAt    time.Time       `json:"createdAt"`
	IsAdmin      bool            `json:"isAdmin"`
	IsGuest      bool            `json:"isGuest"`
	Emails       []*UserEmail    `json:"emails"`
	Identities   []*UserIdentity `json:"identities"`
}

type UserEmail struct {
	ID         string    `json:"id"`
	Email      string    `json:"email"`
	IsPrimary  bool      `json:"isPrimary"`
	VerifiedAt time.Time `json:"verifiedAt"`
}

type UserIdentity struct {
	ID         string       `json:"id"`
	Provider   AuthProvider `json:"provider"`
	Email      *string      `json:"email,omitempty"`
	VerifiedAt time.Time    `json:"verifiedAt"`
}

type AuthProvider string

const (
	AuthProviderGoogle   AuthProvider = "GOOGLE"
	AuthProviderDiscord  AuthProvider = "DISCORD"
	AuthProviderApple    AuthProvider = "APPLE"
	AuthProviderFacebook AuthProvider = "FACEBOOK"
)

var AllAuthProvider = []AuthProvider{
	AuthProviderGoogle,
	AuthProviderDiscord,
	AuthProviderApple,
	AuthProviderFacebook,
}

func (e AuthProvider) IsValid() bool {
	switch e {
	case AuthProviderGoogle, AuthProviderDiscord, AuthProviderApple, AuthProviderFacebook:
		return true
	}
	return false
}

func (e AuthProvider) String() string {
	return string(e)
}

func (e *AuthProvider) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuthProvider(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuthProvider", str)
	}
	return nil
}

func (e AuthProvider) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AuthProvider) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AuthProvider) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AvatarSource string

const (
	AvatarSourceStarter      AvatarSource = "STARTER"
	AvatarSourceSigil        AvatarSource = "SIGIL"
	AvatarSourceSpiritAnimal AvatarSource = "SPIRIT_ANIMAL"
	AvatarSourceNone         AvatarSource = "NONE"
)

var AllAvatarSource = []AvatarSource{
	AvatarSourceStarter,
	AvatarSourceSigil,
	AvatarSourceSpiritAnimal,
	AvatarSourceNone,
}

func (e AvatarSource) IsValid() bool {
	switch e {
	case AvatarSourceStarter, AvatarSourceSigil, AvatarSourceSpiritAnimal, AvatarSourceNone:
		return true
	}
	return false
}

func (e AvatarSource) String() string {
	return string(e)
}

func (e *AvatarSource) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AvatarSource(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AvatarSource", str)
	}
	return nil
}

func (e AvatarSource) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AvatarSource) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AvatarSource) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GameVisibility string

const (
	GameVisibilityDraft          GameVisibility = "DRAFT"
	GameVisibilityPrivateTesting GameVisibility = "PRIVATE_TESTING"
	GameVisibilityPendingReview  GameVisibility = "PENDING_REVIEW"
	GameVisibilityPublic         GameVisibility = "PUBLIC"
)

var AllGameVisibility = []GameVisibility{
	GameVisibilityDraft,
	GameVisibilityPrivateTesting,
	GameVisibilityPendingReview,
	GameVisibilityPublic,
}

func (e GameVisibility) IsValid() bool {
	switch e {
	case GameVisibilityDraft, GameVisibilityPrivateTesting, GameVisibilityPendingReview, GameVisibilityPublic:
		return true
	}
	return false
}

func (e GameVisibility) String() string {
	return string(e)
}

func (e *GameVisibility) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameVisibility(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameVisibility", str)
	}
	return nil
}

func (e GameVisibility) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GameVisibility) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GameVisibility) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type IntegrationCheckStatus string

const (
	IntegrationCheckStatusPass    IntegrationCheckStatus = "PASS"
	IntegrationCheckStatusFail    IntegrationCheckStatus = "FAIL"
	IntegrationCheckStatusSkipped IntegrationCheckStatus = "SKIPPED"
)

var AllIntegrationCheckStatus = []IntegrationCheckStatus{
	IntegrationCheckStatusPass,
	IntegrationCheckStatusFail,
	IntegrationCheckStatusSkipped,
}

func (e IntegrationCheckStatus) IsValid() bool {
	switch e {
	case IntegrationCheckStatusPass, IntegrationCheckStatusFail, IntegrationCheckStatusSkipped:
		return true
	}
	return false
}

func (e IntegrationCheckStatus) String() string {
	return string(e)
}

func (e *IntegrationCheckStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IntegrationCheckStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IntegrationCheckStatus", str)
	}
	return nil
}

func (e IntegrationCheckStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *IntegrationCheckStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e IntegrationCheckStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MatchResultStatus string

const (
	MatchResultStatusCompleted MatchResultStatus = "COMPLETED"
	MatchResultStatusCancelled MatchResultStatus = "CANCELLED"
	MatchResultStatusAbandoned MatchResultStatus = "ABANDONED"
)

var AllMatchResultStatus = []MatchResultStatus{
	MatchResultStatusCompleted,
	MatchResultStatusCancelled,
	MatchResultStatusAbandoned,
}

func (e MatchResultStatus) IsValid() bool {
	switch e {
	case MatchResultStatusCompleted, MatchResultStatusCancelled, MatchResultStatusAbandoned:
		return true
	}
	return false
}

func (e MatchResultStatus) String() string {
	return string(e)
}

func (e *MatchResultStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MatchResultStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MatchResultStatus", str)
	}
	return nil
}

func (e MatchResultStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MatchResultStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MatchResultStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PlayerFinishReason string

const (
	PlayerFinishReasonCompleted  PlayerFinishReason = "COMPLETED"
	PlayerFinishReasonEliminated PlayerFinishReason = "ELIMINATED"
	PlayerFinishReasonForfeit    PlayerFinishReason = "FORFEIT"
	PlayerFinishReasonDisconnect PlayerFinishReason = "DISCONNECT"
)

var AllPlayerFinishReason = []PlayerFinishReason{
	PlayerFinishReasonCompleted,
	PlayerFinishReasonEliminated,
	PlayerFinishReasonForfeit,
	PlayerFinishReasonDisconnect,
}

func (e PlayerFinishReason) IsValid() bool {
	switch e {
	case PlayerFinishReasonCompleted, PlayerFinishReasonEliminated, PlayerFinishReasonForfeit, PlayerFinishReasonDisconnect:
		return true
	}
	return false
}

func (e PlayerFinishReason) String() string {
	return string(e)
}

func (e *PlayerFinishReason) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PlayerFinishReason(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PlayerFinishReason", str)
	}
	return nil
}

func (e PlayerFinishReason) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PlayerFinishReason) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PlayerFinishReason) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type QueueStatus string

const (
	QueueStatusWaiting QueueStatus = "WAITING"
	QueueStatusMatched QueueStatus = "MATCHED"
	QueueStatusLeft    QueueStatus = "LEFT"
)

var AllQueueStatus = []QueueStatus{
	QueueStatusWaiting,
	QueueStatusMatched,
	QueueStatusLeft,
}

func (e QueueStatus) IsValid() bool {
	switch e {
	case QueueStatusWaiting, QueueStatusMatched, QueueStatusLeft:
		return true
	}
	return false
}

func (e QueueStatus) String() string {
	return string(e)
}

func (e *QueueStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = QueueStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid QueueStatus", str)
	}
	return nil
}

func (e QueueStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *QueueStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e QueueStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RegroupState string

const (
	RegroupStateIn      RegroupState = "IN"
	RegroupStateOut     RegroupState = "OUT"
	RegroupStatePending RegroupState = "PENDING"
)

var AllRegroupState = []RegroupState{
	RegroupStateIn,
	RegroupStateOut,
	RegroupStatePending,
}

func (e RegroupState) IsValid() bool {
	switch e {
	case RegroupStateIn, RegroupStateOut, RegroupStatePending:
		return true
	}
	return false
}

func (e RegroupState) String() string {
	return string(e)
}

func (e *RegroupState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RegroupState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RegroupState", str)
	}
	return nil
}

func (e RegroupState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RegroupState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RegroupState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RequirementOperator string

const (
	RequirementOperatorAll RequirementOperator = "ALL"
	RequirementOperatorAny RequirementOperator = "ANY"
)

var AllRequirementOperator = []RequirementOperator{
	RequirementOperatorAll,
	RequirementOperatorAny,
}

func (e RequirementOperator) IsValid() bool {
	switch e {
	case RequirementOperatorAll, RequirementOperatorAny:
		return true
	}
	return false
}

func (e RequirementOperator) String() string {
	return string(e)
}

func (e *RequirementOperator) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RequirementOperator(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RequirementOperator", str)
	}
	return nil
}

func (e RequirementOperator) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RequirementOperator) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RequirementOperator) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SessionStatus string

const (
	SessionStatusPending SessionStatus = "PENDING"
	SessionStatusActive  SessionStatus = "ACTIVE"
	SessionStatusEnded   SessionStatus = "ENDED"
)

var AllSessionStatus = []SessionStatus{
	SessionStatusPending,
	SessionStatusActive,
	SessionStatusEnded,
}

func (e SessionStatus) IsValid() bool {
	switch e {
	case SessionStatusPending, SessionStatusActive, SessionStatusEnded:
		return true
	}
	return false
}

func (e SessionStatus) String() string {
	return string(e)
}

func (e *SessionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SessionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SessionStatus", str)
	}
	return nil
}

func (e SessionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SessionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SessionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SpiritAnimalReadingStatus string

const (
	SpiritAnimalReadingStatusGeneratingQuestions SpiritAnimalReadingStatus = "GENERATING_QUESTIONS"
	SpiritAnimalReadingStatusAwaitingAnswers     SpiritAnimalReadingStatus = "AWAITING_ANSWERS"
	SpiritAnimalReadingStatusProcessing          SpiritAnimalReadingStatus = "PROCESSING"
	SpiritAnimalReadingStatusReady               SpiritAnimalReadingStatus = "READY"
	SpiritAnimalReadingStatusCompleted           SpiritAnimalReadingStatus = "COMPLETED"
	SpiritAnimalReadingStatusFailed              SpiritAnimalReadingStatus = "FAILED"
)

var AllSpiritAnimalReadingStatus = []SpiritAnimalReadingStatus{
	SpiritAnimalReadingStatusGeneratingQuestions,
	SpiritAnimalReadingStatusAwaitingAnswers,
	SpiritAnimalReadingStatusProcessing,
	SpiritAnimalReadingStatusReady,
	SpiritAnimalReadingStatusCompleted,
	SpiritAnimalReadingStatusFailed,
}

func (e SpiritAnimalReadingStatus) IsValid() bool {
	switch e {
	case SpiritAnimalReadingStatusGeneratingQuestions, SpiritAnimalReadingStatusAwaitingAnswers, SpiritAnimalReadingStatusProcessing, SpiritAnimalReadingStatusReady, SpiritAnimalReadingStatusCompleted, SpiritAnimalReadingStatusFailed:
		return true
	}
	return false
}

func (e SpiritAnimalReadingStatus) String() string {
	return string(e)
}

func (e *SpiritAnimalReadingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SpiritAnimalReadingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SpiritAnimalReadingStatus", str)
	}
	return nil
}

func (e SpiritAnimalReadingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SpiritAnimalReadingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SpiritAnimalReadingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
