package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"strings"

	"github.com/scruffyprodigy/joinquest/graph/generated"
	"github.com/scruffyprodigy/joinquest/graph/model"
	"github.com/scruffyprodigy/joinquest/internal/auth"
	"github.com/scruffyprodigy/joinquest/internal/gameurl"
	"github.com/scruffyprodigy/joinquest/internal/store"
)

// PlayerActivity is the resolver for the playerActivity field.
func (r *gameResolver) PlayerActivity(ctx context.Context, obj *model.Game) (*model.GamePlayerActivity, error) {
	gameID, err := parseUUID(obj.ID, "game id")
	if err != nil {
		return nil, err
	}
	counts, err := r.liveCounts(ctx, gameID)
	if err != nil {
		return nil, err
	}
	return &model.GamePlayerActivity{Playing: counts.Playing, Queued: counts.Queued}, nil
}

// Modes is the resolver for the modes field.
func (r *gameResolver) Modes(ctx context.Context, obj *model.Game) ([]*model.GameMode, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	gameID, err := parseUUID(obj.ID, "game id")
	if err != nil {
		return nil, err
	}
	modes, err := st.ListGameModesByGameID(ctx, gameID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLGameModes(modes), nil
}

// Seats is the resolver for the seats field.
func (r *gameModeResolver) Seats(ctx context.Context, obj *model.GameMode) ([]*model.GameModeSeat, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	modeID, err := parseUUID(obj.ID, "mode id")
	if err != nil {
		return nil, err
	}
	seats, err := st.ListGameModeSeats(ctx, modeID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLGameModeSeats(seats), nil
}

// QueuePaths is the resolver for the queuePaths field.
func (r *gameModeResolver) QueuePaths(ctx context.Context, obj *model.GameMode) ([]*model.GameModeQueuePath, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	modeID, err := parseUUID(obj.ID, "mode id")
	if err != nil {
		return nil, err
	}
	mode, err := st.GetGameModeByID(ctx, modeID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLQueuePaths(mode.SeatTemplate)
}

// Queues is the resolver for the queues field.
func (r *gameModeResolver) Queues(ctx context.Context, obj *model.GameMode) ([]*model.ModeQueue, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	modeID, err := parseUUID(obj.ID, "mode id")
	if err != nil {
		return nil, err
	}
	queues, err := st.ListModeQueuesByModeID(ctx, modeID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLModeQueues(queues), nil
}

// Eligibility is the resolver for the eligibility field.
func (r *gameModeResolver) Eligibility(ctx context.Context, obj *model.GameMode, playerID string) (*model.ModeEligibility, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	authUserID, err := requireAuthUserID(ctx)
	if err != nil {
		// Fail open: no valid session (e.g. an expired cookie) shouldn't blank
		// out the whole catalog page over one nullable field.
		return &model.ModeEligibility{Accessible: true}, nil
	}
	requestedID, err := parseUUID(playerID, "player id")
	if err != nil {
		// Fail open: a malformed argument isn't a security concern here.
		return &model.ModeEligibility{Accessible: true}, nil
	}
	if requestedID != authUserID {
		// Hard error: a well-formed but mismatched player id is a genuine
		// cross-player authorization violation, not something to paper over.
		return nil, fmt.Errorf("cannot query eligibility for another player")
	}

	modeID, err := parseUUID(obj.ID, "mode id")
	if err != nil {
		return nil, err
	}
	mode, err := st.GetGameModeByID(ctx, modeID)
	if err != nil {
		return nil, err
	}
	game, err := st.GetGameByID(ctx, mode.GameID)
	if err != nil {
		return nil, err
	}
	if game.APIBaseURL == nil || *game.APIBaseURL == "" {
		return &model.ModeEligibility{Accessible: true}, nil
	}

	batch, err := r.eligibilityCache().Get(ctx, game.ID.String(), *game.APIBaseURL, playerID)
	if err != nil {
		// Fail open: a game server we can't reach doesn't block play.
		return &model.ModeEligibility{Accessible: true}, nil
	}

	elig, ok := batch[mode.ModeKey]
	if !ok {
		return &model.ModeEligibility{Accessible: true}, nil
	}
	return toGraphQLModeEligibility(elig), nil
}

// PreQueueGroups is the resolver for the preQueueGroups field.
func (r *gameModeResolver) PreQueueGroups(ctx context.Context, obj *model.GameMode) ([]*model.PreQueueGroup, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	modeID, err := parseUUID(obj.ID, "mode id")
	if err != nil {
		return nil, err
	}
	mode, err := st.GetGameModeByID(ctx, modeID)
	if err != nil {
		return nil, err
	}
	return toGraphQLPreQueueGroups(declaredGroups(mode)), nil
}

// QueueOptions is the resolver for the queueOptions field.
func (r *gameModeResolver) QueueOptions(ctx context.Context, obj *model.GameMode, playerID string) (*model.QueueOptions, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	authUserID, err := requireAuthUserID(ctx)
	if err != nil {
		// No session means no player to fetch a roster for. Null, not an error:
		// a signed-out browse of the catalog still renders.
		return nil, nil
	}
	requestedID, err := parseUUID(playerID, "player id")
	if err != nil {
		return nil, nil
	}
	if requestedID != authUserID {
		// A well-formed but mismatched id would leak another player's unlocks.
		return nil, fmt.Errorf("cannot query queue options for another player")
	}

	modeID, err := parseUUID(obj.ID, "mode id")
	if err != nil {
		return nil, err
	}
	mode, err := st.GetGameModeByID(ctx, modeID)
	if err != nil {
		return nil, err
	}
	groups := declaredGroups(mode)
	if len(groups) == 0 {
		// Null rather than an empty roster: this mode has no pre-queue step at
		// all, which is different from having one we could not load.
		return nil, nil
	}
	game, err := st.GetGameByID(ctx, mode.GameID)
	if err != nil {
		return nil, err
	}

	roster, err := r.playerRoster(ctx, game, mode, groups, playerID)
	if err != nil {
		// Deliberately not fail-open. There is no roster to guess at, so the
		// picker shows an error and this mode alone stops accepting joins.
		return unavailableQueueOptions("This game can't tell us your options right now. Try again in a moment."), nil
	}
	return toGraphQLQueueOptions(roster), nil
}

// WaitingCount is the resolver for the waitingCount field.
func (r *modeQueueResolver) WaitingCount(ctx context.Context, obj *model.ModeQueue) (int, error) {
	st, err := r.requireStore()
	if err != nil {
		return 0, err
	}
	queueID, err := parseUUID(obj.ID, "queue id")
	if err != nil {
		return 0, err
	}
	return st.CountWaitingInModeQueue(ctx, queueID)
}

// RegisterGame is the resolver for the registerGame field.
func (r *mutationResolver) RegisterGame(ctx context.Context, input model.RegisterGameInput) (*model.RegisterGamePayload, error) {
	if _, err := r.requireAdmin(ctx); err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	manifest, err := r.manifestFetcher().Fetch(ctx, input.APIBaseURL, "")
	if err != nil {
		return nil, err
	}

	if err := gameurl.ValidateOutboundURL(ctx, input.APIBaseURL, auth.IsProductionEnv()); err != nil {
		return nil, fmt.Errorf("apiBaseUrl: %w", err)
	}

	var description *string
	if input.Description != nil {
		trimmed := strings.TrimSpace(*input.Description)
		if trimmed != "" {
			description = &trimmed
		}
	}
	name := ""
	if input.Name != nil {
		name = strings.TrimSpace(*input.Name)
	}

	iconURL := strings.TrimSpace(input.IconURL)
	if iconURL == "" {
		return nil, fmt.Errorf("iconUrl is required")
	}
	heroURL := strings.TrimSpace(input.HeroURL)
	if heroURL == "" {
		return nil, fmt.Errorf("heroUrl is required")
	}

	result, err := st.RegisterGame(ctx, store.RegisterGameParams{
		Slug:        input.Slug,
		Name:        name,
		Description: description,
		IconURL:     iconURL,
		HeroURL:     heroURL,
		APIBaseURL:  input.APIBaseURL,
	}, manifest)
	if err != nil {
		return nil, err
	}

	if err := r.publishKickedWaiters(ctx, result.Kicked); err != nil {
		return nil, err
	}

	serviceToken, err := auth.FormatGameServiceToken(result.Game.ID)
	if err != nil {
		return nil, err
	}

	return &model.RegisterGamePayload{
		Game:          ToGraphQLGame(result.Game),
		WebhookSecret: result.WebhookSecret,
		ServiceToken:  serviceToken,
	}, nil
}

// RefreshGameManifest is the resolver for the refreshGameManifest field.
func (r *mutationResolver) RefreshGameManifest(ctx context.Context, gameID string) (*model.Game, error) {
	if _, err := r.requireAdmin(ctx); err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	id, err := parseUUID(gameID, "game id")
	if err != nil {
		return nil, err
	}
	game, err := st.GetGameByID(ctx, id)
	if err != nil {
		return nil, err
	}

	result, err := r.syncGameManifest(ctx, game)
	if err != nil {
		return nil, err
	}

	if err := r.publishKickedWaiters(ctx, result.Kicked); err != nil {
		return nil, err
	}

	return ToGraphQLGame(result.Game), nil
}

// GameMode returns generated.GameModeResolver implementation.
func (r *Resolver) GameMode() generated.GameModeResolver { return &gameModeResolver{r} }

// ModeQueue returns generated.ModeQueueResolver implementation.
func (r *Resolver) ModeQueue() generated.ModeQueueResolver { return &modeQueueResolver{r} }

type gameModeResolver struct{ *Resolver }
type modeQueueResolver struct{ *Resolver }
