package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/scruffyprodigy/playhub/graph/model"
	"github.com/scruffyprodigy/playhub/internal/pubsub"
	"github.com/scruffyprodigy/playhub/internal/store"
)

// ReportPlayerFinished is the resolver for the reportPlayerFinished field.
func (r *mutationResolver) ReportPlayerFinished(ctx context.Context, matchID string, lobbyUserID string, reason model.PlayerFinishReason, placement *int, metadata map[string]any) (bool, error) {
	if err := requireGameServiceAuth(ctx); err != nil {
		return false, err
	}
	st, err := r.requireStore()
	if err != nil {
		return false, err
	}

	sessionID, session, err := loadAuthorizedGameSession(ctx, st, matchID)
	if err != nil {
		return false, err
	}
	playerID, err := parseUUID(lobbyUserID, "lobby user id")
	if err != nil {
		return false, err
	}

	now := time.Now()
	if err := st.MarkParticipantFinished(ctx, sessionID, playerID, now); err != nil {
		return false, err
	}
	if err := st.RecordPlayerFinish(ctx, sessionID, playerID, string(reason), placement, metadata); err != nil {
		return false, err
	}
	if session.ModeQueueID != nil {
		if err := st.ReleaseUserMatchedQueue(ctx, *session.ModeQueueID, playerID); err != nil {
			return false, err
		}
	}

	remaining, err := st.CountActiveParticipants(ctx, sessionID)
	if err != nil {
		return false, err
	}
	if remaining == 0 {
		if err := st.CompleteSession(ctx, sessionID, now); err != nil && !errors.Is(err, store.ErrNotFound) {
			return false, err
		}
	}

	if err := r.publishMatchEvent(ctx, sessionID, pubsub.MatchEventPlayerFinished); err != nil {
		return false, err
	}

	return true, nil
}

// ReportMatchResult is the resolver for the reportMatchResult field.
func (r *mutationResolver) ReportMatchResult(ctx context.Context, matchID string, status model.MatchResultStatus, winnerLobbyUserIds []string, metadata map[string]any) (bool, error) {
	if err := requireGameServiceAuth(ctx); err != nil {
		return false, err
	}
	st, err := r.requireStore()
	if err != nil {
		return false, err
	}

	sessionID, _, err := loadAuthorizedGameSession(ctx, st, matchID)
	if err != nil {
		return false, err
	}

	winnerIDs := make([]uuid.UUID, 0, len(winnerLobbyUserIds))
	for _, raw := range winnerLobbyUserIds {
		id, err := parseUUID(raw, "winner lobby user id")
		if err != nil {
			return false, err
		}
		winnerIDs = append(winnerIDs, id)
	}
	if err := st.RecordMatchResult(ctx, sessionID, string(status), winnerIDs, metadata, time.Now()); err != nil {
		return false, err
	}

	table, _ := st.GetRoomTableBySessionID(ctx, sessionID)

	if err := st.CompleteSession(ctx, sessionID, time.Now()); err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return true, nil
		}
		return false, err
	}

	if table != nil {
		_ = r.publishTableUpdated(ctx, table.RoomID, table.ID)
	}
	_ = r.publishMatchEvent(ctx, sessionID, pubsub.MatchEventResult)

	return true, nil
}

// PlayAgain is the resolver for the playAgain field. It converges every accepting player on
// the single regroup table for this match — ClaimRegroupTable's row lock is what makes that
// hold under concurrent calls, this resolver only reports the result.
func (r *mutationResolver) PlayAgain(ctx context.Context, matchID string) (*model.PlayAgainResult, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	sessionID, err := parseUUID(strings.TrimSpace(matchID), "match id")
	if err != nil {
		return nil, err
	}
	if err := requireMatchParticipant(ctx, st, sessionID, userID); err != nil {
		return nil, err
	}

	table, room, err := st.ClaimRegroupTable(ctx, sessionID, userID)
	if err != nil {
		return nil, regroupClientError(err)
	}

	seats, err := st.ListTableSeats(ctx, table.ID)
	if err != nil {
		return nil, err
	}
	seated := false
	for _, seat := range seats {
		if seat.UserID == userID {
			seated = true
			break
		}
	}

	if err := r.publishTableUpdated(ctx, table.RoomID, table.ID); err != nil {
		return nil, err
	}
	if err := r.publishMatchEvent(ctx, sessionID, pubsub.MatchEventRegroup); err != nil {
		return nil, err
	}

	return &model.PlayAgainResult{
		Table:      toGraphQLTable(table),
		InviteCode: room.InviteCode,
		Seated:     seated,
	}, nil
}

// DeclinePlayAgain is the resolver for the declinePlayAgain field. It records the caller as
// out and routes them through the same return-destination logic as the returnDestination
// query, so a decliner and someone who never played again land on the same result.
func (r *mutationResolver) DeclinePlayAgain(ctx context.Context, matchID string) (*model.ReturnDestination, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	sessionID, err := parseUUID(strings.TrimSpace(matchID), "match id")
	if err != nil {
		return nil, err
	}
	if err := requireMatchParticipant(ctx, st, sessionID, userID); err != nil {
		return nil, err
	}
	if err := st.DeclineRegroup(ctx, sessionID, userID, time.Now()); err != nil && !errors.Is(err, store.ErrNotFound) {
		return nil, err
	}
	if err := r.publishMatchEvent(ctx, sessionID, pubsub.MatchEventRegroup); err != nil {
		return nil, err
	}
	return resolveReturnDestination(ctx, st, sessionID, userID)
}

// ReturnDestination is the resolver for the returnDestination field.
func (r *queryResolver) ReturnDestination(ctx context.Context, matchID *string) (*model.ReturnDestination, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	defaultDest := &model.ReturnDestination{Path: "/", Kind: store.ReturnKindCatalogLFG}

	var sessionID uuid.UUID
	if matchID != nil && strings.TrimSpace(*matchID) != "" {
		sessionID, err = parseUUID(strings.TrimSpace(*matchID), "match id")
		if err != nil {
			return nil, err
		}
	} else {
		view, vErr := st.GetUserActiveIntent(ctx, userID)
		if vErr != nil {
			return nil, vErr
		}
		if view == nil || !view.Matched || view.SessionID == nil {
			return defaultDest, nil
		}
		sessionID = *view.SessionID
	}

	return resolveReturnDestination(ctx, st, sessionID, userID)
}

// MatchResult is the resolver for the matchResult field.
func (r *queryResolver) MatchResult(ctx context.Context, matchID string) (*model.MatchResult, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	sessionID, err := parseUUID(strings.TrimSpace(matchID), "match id")
	if err != nil {
		return nil, err
	}
	if err := requireMatchParticipant(ctx, st, sessionID, userID); err != nil {
		return nil, err
	}
	return loadMatchResultModel(ctx, st, sessionID)
}

// MatchResultUpdated is the resolver for the matchResultUpdated field.
func (r *subscriptionResolver) MatchResultUpdated(ctx context.Context, matchID string) (<-chan *model.MatchResult, error) {
	if r.PubSub == nil {
		return nil, fmt.Errorf("pubsub is not configured")
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	sessionID, err := parseUUID(strings.TrimSpace(matchID), "match id")
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	if err := requireMatchParticipant(ctx, st, sessionID, userID); err != nil {
		return nil, err
	}

	initial, err := loadMatchResultModel(ctx, st, sessionID)
	if err != nil {
		return nil, err
	}

	messages, unsubscribe, err := r.PubSub.Subscribe(ctx, pubsub.MatchChannel(sessionID.String()))
	if err != nil {
		return nil, err
	}

	updates := make(chan *model.MatchResult, 4)
	go func() {
		defer close(updates)
		defer unsubscribe()

		if initial != nil {
			select {
			case updates <- initial:
			case <-ctx.Done():
				return
			}
		}

		for {
			select {
			case <-ctx.Done():
				return
			case payload, ok := <-messages:
				if !ok {
					return
				}
				if _, err := pubsub.UnmarshalMatchEvent(payload); err != nil {
					continue
				}
				result, err := loadMatchResultModel(ctx, st, sessionID)
				if err != nil {
					continue
				}
				select {
				case updates <- result:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return updates, nil
}
