package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/scruffyprodigy/joinquest/graph/model"
	"github.com/scruffyprodigy/joinquest/internal/pubsub"
	"github.com/scruffyprodigy/joinquest/internal/store"
)

// ReportPlayerFinished is the resolver for the reportPlayerFinished field.
func (r *mutationResolver) ReportPlayerFinished(ctx context.Context, matchID string, lobbyUserID string, reason model.PlayerFinishReason, placement *int, metadata map[string]any) (bool, error) {
	if err := requireGameServiceAuth(ctx); err != nil {
		return false, err
	}
	st, err := r.requireStore()
	if err != nil {
		return false, err
	}

	sessionID, session, err := loadAuthorizedGameSession(ctx, st, matchID)
	if err != nil {
		return false, err
	}
	playerID, err := parseUUID(lobbyUserID, "lobby user id")
	if err != nil {
		return false, err
	}

	now := time.Now()
	// The reported payload is persisted first, and it — not the mark below — is what
	// validates the player: RecordPlayerFinish matches the participant row regardless of
	// finished_at, so an unknown lobby user id still surfaces as ErrNotFound.
	if err := st.RecordPlayerFinish(ctx, sessionID, playerID, string(reason), placement, metadata); err != nil {
		return false, err
	}
	// ErrNotFound here means the player already reached /return and AcknowledgePlayerReturn
	// stamped finished_at first (MarkParticipantFinished has AND finished_at IS NULL). The
	// browser winning that race must not cost the game's placement report, and must not hand
	// the game server a failure it would retry forever against an applied write.
	if err := st.MarkParticipantFinished(ctx, sessionID, playerID, now); err != nil && !errors.Is(err, store.ErrNotFound) {
		return false, err
	}
	if session.ModeQueueID != nil {
		if err := st.ReleaseUserMatchedQueue(ctx, *session.ModeQueueID, playerID); err != nil {
			return false, err
		}
	}

	remaining, err := st.CountActiveParticipants(ctx, sessionID)
	if err != nil {
		return false, err
	}
	if remaining == 0 {
		if err := st.CompleteSession(ctx, sessionID, now); err != nil && !errors.Is(err, store.ErrNotFound) {
			return false, err
		}
	}

	// Fire-and-forget: the finish is already committed, and a pub/sub blip must not tell
	// the game server its lifecycle report failed (it would retry an applied write).
	_ = r.publishMatchEvent(ctx, sessionID, pubsub.MatchEventPlayerFinished)

	return true, nil
}

// ReportMatchResult is the resolver for the reportMatchResult field.
func (r *mutationResolver) ReportMatchResult(ctx context.Context, matchID string, status model.MatchResultStatus, winnerLobbyUserIds []string, metadata map[string]any) (bool, error) {
	if err := requireGameServiceAuth(ctx); err != nil {
		return false, err
	}
	st, err := r.requireStore()
	if err != nil {
		return false, err
	}

	sessionID, _, err := loadAuthorizedGameSession(ctx, st, matchID)
	if err != nil {
		return false, err
	}

	winnerIDs := make([]uuid.UUID, 0, len(winnerLobbyUserIds))
	for _, raw := range winnerLobbyUserIds {
		id, err := parseUUID(raw, "winner lobby user id")
		if err != nil {
			return false, err
		}
		winnerIDs = append(winnerIDs, id)
	}
	if err := st.RecordMatchResult(ctx, sessionID, string(status), winnerIDs, metadata, time.Now()); err != nil {
		return false, err
	}

	table, _ := st.GetRoomTableBySessionID(ctx, sessionID)

	// ErrNotFound means something completed the session before this call. Usually that
	// is the last reportPlayerFinished, and the result still stands — so this stays a
	// success rather than a failure the game server would retry against an applied
	// write. But it is also what a bad cleanup job looks like from in here (JQ-171),
	// and this used to be the one place that knew and said nothing: steps two and three
	// of the completion never ran, and no signal marked it. Record it either way and
	// let the rate say which it is.
	completeErr := st.CompleteSession(ctx, sessionID, time.Now())
	if completeErr != nil && !errors.Is(completeErr, store.ErrNotFound) {
		return false, completeErr
	}
	if errors.Is(completeErr, store.ErrNotFound) {
		log.Printf("reportMatchResult: completion pre-empted session=%s status=%s; result recorded, table reset skipped",
			sessionID, status)
		r.signals().Count(metricCompletionPreempted, 1, map[string]string{
			"mutation": "reportMatchResult",
		})
	}
	if completeErr == nil && table != nil {
		_ = r.publishTableUpdated(ctx, table.RoomID, table.ID)
	}

	// Published on every path that recorded a result: subscribers watching the results
	// screen flip to the final standings here, and an already-completed session must
	// not silence that.
	_ = r.publishMatchEvent(ctx, sessionID, pubsub.MatchEventResult)

	return true, nil
}

// PlayAgain is the resolver for the playAgain field. It converges every accepting player on
// the single regroup table for this match — ClaimRegroupTable's row lock is what makes that
// hold under concurrent calls, this resolver only reports the result.
func (r *mutationResolver) PlayAgain(ctx context.Context, matchID string) (*model.PlayAgainResult, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	sessionID, err := parseUUID(strings.TrimSpace(matchID), "match id")
	if err != nil {
		return nil, err
	}
	if err := requireMatchParticipant(ctx, st, sessionID, userID); err != nil {
		return nil, err
	}

	table, room, err := st.ClaimRegroupTable(ctx, sessionID, userID)
	if err != nil {
		return nil, regroupClientError(err)
	}

	seats, err := st.ListTableSeats(ctx, table.ID)
	if err != nil {
		return nil, err
	}
	seated := false
	for _, seat := range seats {
		if seat.UserID == userID {
			seated = true
			break
		}
	}

	if err := r.publishTableUpdated(ctx, table.RoomID, table.ID); err != nil {
		return nil, err
	}
	// Fire-and-forget: the seat is already claimed, so a publish failure must not cost
	// the caller the invite code for the table they are now sitting at.
	_ = r.publishMatchEvent(ctx, sessionID, pubsub.MatchEventRegroup)

	return &model.PlayAgainResult{
		Table:      toGraphQLTable(table),
		InviteCode: room.InviteCode,
		Seated:     seated,
	}, nil
}

// DeclinePlayAgain is the resolver for the declinePlayAgain field. It records the caller as
// out and routes them through the same return-destination logic as the returnDestination
// query, so a decliner and someone who never played again land on the same result.
func (r *mutationResolver) DeclinePlayAgain(ctx context.Context, matchID string) (*model.ReturnDestination, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	sessionID, err := parseUUID(strings.TrimSpace(matchID), "match id")
	if err != nil {
		return nil, err
	}
	if err := requireMatchParticipant(ctx, st, sessionID, userID); err != nil {
		return nil, err
	}
	release, err := st.DeclineRegroup(ctx, sessionID, userID, time.Now())
	if err != nil && !errors.Is(err, store.ErrNotFound) {
		return nil, err
	}
	// Fire-and-forget: the decline is already recorded, so a publish failure must not
	// strand the caller on the results screen without a return destination.
	if release != nil {
		// The freed seat is a table change, and everyone at /room/{code} watches
		// tableUpdated rather than matchResultUpdated — without this they keep seeing the
		// decliner seated. playAgain publishes both for the same reason.
		_ = r.publishTableUpdated(ctx, release.RoomID, release.TableID)
	}
	_ = r.publishMatchEvent(ctx, sessionID, pubsub.MatchEventRegroup)
	return resolveReturnDestination(ctx, st, sessionID, userID)
}

// ReturnDestination is the resolver for the returnDestination field.
func (r *queryResolver) ReturnDestination(ctx context.Context, matchID *string) (*model.ReturnDestination, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	defaultDest := &model.ReturnDestination{Path: "/", Kind: store.ReturnKindCatalogLFG}

	var sessionID uuid.UUID
	if matchID != nil && strings.TrimSpace(*matchID) != "" {
		sessionID, err = parseUUID(strings.TrimSpace(*matchID), "match id")
		if err != nil {
			return nil, err
		}
	} else {
		view, vErr := st.GetUserActiveIntent(ctx, userID)
		if vErr != nil {
			return nil, vErr
		}
		if view == nil || !view.Matched || view.SessionID == nil {
			return defaultDest, nil
		}
		sessionID = *view.SessionID
	}

	return resolveReturnDestination(ctx, st, sessionID, userID)
}

// MatchResult is the resolver for the matchResult field.
func (r *queryResolver) MatchResult(ctx context.Context, matchID string) (*model.MatchResult, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	sessionID, err := parseUUID(strings.TrimSpace(matchID), "match id")
	if err != nil {
		return nil, err
	}
	if err := requireMatchParticipant(ctx, st, sessionID, userID); err != nil {
		return nil, err
	}
	return loadMatchResultModel(ctx, st, sessionID, userID)
}

// MatchResultUpdated is the resolver for the matchResultUpdated field.
func (r *subscriptionResolver) MatchResultUpdated(ctx context.Context, matchID string) (<-chan *model.MatchResult, error) {
	if r.PubSub == nil {
		return nil, fmt.Errorf("pubsub is not configured")
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	sessionID, err := parseUUID(strings.TrimSpace(matchID), "match id")
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	if err := requireMatchParticipant(ctx, st, sessionID, userID); err != nil {
		return nil, err
	}

	initial, err := loadMatchResultModel(ctx, st, sessionID, userID)
	if err != nil {
		return nil, err
	}

	messages, unsubscribe, err := r.PubSub.Subscribe(ctx, pubsub.MatchChannel(sessionID.String()))
	if err != nil {
		return nil, err
	}

	updates := make(chan *model.MatchResult, 4)
	go func() {
		defer close(updates)
		defer unsubscribe()

		if initial != nil {
			select {
			case updates <- initial:
			case <-ctx.Done():
				return
			}
		}

		for {
			select {
			case <-ctx.Done():
				return
			case payload, ok := <-messages:
				if !ok {
					return
				}
				if _, err := pubsub.UnmarshalMatchEvent(payload); err != nil {
					continue
				}
				result, err := loadMatchResultModel(ctx, st, sessionID, userID)
				if err != nil {
					continue
				}
				select {
				case updates <- result:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return updates, nil
}
