package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"

	"github.com/scruffyprodigy/joinquest/graph/model"
	"github.com/scruffyprodigy/joinquest/internal/auth"
	"github.com/scruffyprodigy/joinquest/internal/store"
)

// SavePushSubscription is the resolver for the savePushSubscription field.
func (r *mutationResolver) SavePushSubscription(ctx context.Context, input model.SavePushSubscriptionInput) (*model.PushCapability, error) {
	// requireAuthUserID, not requireIdentityUserID: registering for
	// notifications is not entering play, so a nameless guest still needs it.
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	if _, err := st.SavePushSubscription(ctx, store.SavePushSubscriptionParams{
		UserID:    userID,
		Endpoint:  input.Endpoint,
		P256dh:    input.P256dh,
		Auth:      input.Auth,
		UserAgent: auth.UserAgentFromContext(ctx),
	}); err != nil {
		return nil, err
	}

	return r.pushCapabilityFor(ctx, userID)
}

// DeletePushSubscription is the resolver for the deletePushSubscription field.
func (r *mutationResolver) DeletePushSubscription(ctx context.Context, endpoint string) (*model.PushCapability, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	if err := st.DeletePushSubscription(ctx, userID, endpoint); err != nil {
		return nil, err
	}

	return r.pushCapabilityFor(ctx, userID)
}

// VerifyPushSubscription is the resolver for the verifyPushSubscription field.
func (r *mutationResolver) VerifyPushSubscription(ctx context.Context, endpoint string) (*model.PushVerification, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}

	sent, err := r.StartPushVerification(ctx, userID, endpoint)
	if err != nil {
		return nil, err
	}

	// Deliberately the pre-ack snapshot: the round trip has not finished, and
	// reporting anything else would be the promise this whole mechanism exists
	// to avoid making.
	capability, err := r.pushCapabilityFor(ctx, userID)
	if err != nil {
		return nil, err
	}
	return &model.PushVerification{Sent: sent, Capability: capability}, nil
}

// ConfirmPushVerification is the resolver for the confirmPushVerification field.
func (r *mutationResolver) ConfirmPushVerification(ctx context.Context, token string) (*model.PushVerificationResult, error) {
	// No auth check: the token is the credential. It is single-use, short
	// lived, and only the browser the push reached is holding it -- and that
	// browser may be acking for a page that has already closed, which is
	// exactly the case this has to keep working for.
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	if _, err := st.ConfirmPushSubscriptionVerification(ctx, token); err != nil {
		if errors.Is(err, store.ErrPushVerificationNotFound) {
			// Unknown, replayed, or stale. A normal outcome, not a fault: say
			// "not verified" rather than raising an error the caller would
			// have to tell apart from a real one.
			return &model.PushVerificationResult{Verified: false}, nil
		}
		return nil, err
	}
	return &model.PushVerificationResult{Verified: true}, nil
}

// PushCapability is the resolver for the pushCapability field.
func (r *queryResolver) PushCapability(ctx context.Context) (*model.PushCapability, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		// No user to attach a subscription to, so this is "not available",
		// not an error.
		return &model.PushCapability{Reachable: false, SubscriptionCount: 0}, nil
	}
	return r.pushCapabilityFor(ctx, userID)
}
