package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"strings"

	"github.com/google/uuid"
	"github.com/scruffyprodigy/joinquest/graph/model"
	"github.com/scruffyprodigy/joinquest/internal/auth"
	"github.com/scruffyprodigy/joinquest/internal/store"
)

// SavePushSubscription is the resolver for the savePushSubscription field.
func (r *mutationResolver) SavePushSubscription(ctx context.Context, input model.SavePushSubscriptionInput) (*model.PushCapability, error) {
	// requireAuthUserID, not requireIdentityUserID: registering for
	// notifications is not putting a player into play, and a guest who has not
	// yet picked a name still needs to be told when their match is ready.
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	if _, err := st.SavePushSubscription(ctx, store.SavePushSubscriptionParams{
		UserID:    userID,
		Endpoint:  input.Endpoint,
		P256dh:    input.P256dh,
		Auth:      input.Auth,
		UserAgent: auth.UserAgentFromContext(ctx),
	}); err != nil {
		return nil, err
	}

	return r.pushCapabilityFor(ctx, userID)
}

// DeletePushSubscription is the resolver for the deletePushSubscription field.
func (r *mutationResolver) DeletePushSubscription(ctx context.Context, endpoint string) (*model.PushCapability, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	if err := st.DeletePushSubscription(ctx, userID, endpoint); err != nil {
		return nil, err
	}

	return r.pushCapabilityFor(ctx, userID)
}

// PushCapability is the resolver for the pushCapability field.
func (r *queryResolver) PushCapability(ctx context.Context) (*model.PushCapability, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		// A signed-out visitor is simply unreachable. Returning the public key
		// anyway would be useless -- there is no user to attach a subscription
		// to -- so this is a plain "not available", not an error.
		return &model.PushCapability{Reachable: false, SubscriptionCount: 0}, nil
	}
	return r.pushCapabilityFor(ctx, userID)
}

// pushCapabilityFor builds the capability snapshot the frontend gates the
// "stay queued while I'm away" affordance on.
//
// The public key is reported only when this deployment can actually sign a
// push. Reporting it while unconfigured would let the browser subscribe to an
// endpoint nothing will ever send to, which is precisely the false
// reachability the ticket warns is worse than offering nothing.
func (r *Resolver) pushCapabilityFor(ctx context.Context, userID uuid.UUID) (*model.PushCapability, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	subs, err := st.ListPushSubscriptions(ctx, userID)
	if err != nil {
		return nil, err
	}

	out := &model.PushCapability{
		SubscriptionCount: len(subs),
	}
	if key := strings.TrimSpace(r.pushSender().PublicKey()); key != "" {
		out.PublicKey = &key
		// Reachability requires both a stored subscription and a deployment
		// that can send to it. Either alone is not a delivered notification.
		out.Reachable = len(subs) > 0
	}
	return out, nil
}
